export const LOCATION_DATA = {
    "India": {
        "Andaman": [
            "Bedfordshire",
            "Berkshire",
            "Buckinghamshire",
            "Cambridgeshire",
            "Cheshire",
            "Cornwall",
            "Cumbria",
            "Derbyshire",
            "Devon",
            "Dorset",
            "Durham",
            "Essex",
            "Gloucestershire",
            "Hampshire",
            "Hertfordshire",
            "Huntingdonshire",
            "Kent",
            "Lancashire",
            "Leicestershire",
            "Lincolnshire",
            "Middlesex",
            "Norfolk",
            "Northamptonshire",
            "Northumberland",
            "Nottinghamshire",
            "Oxfordshire",
            "Rutland",
            "Shropshire",
            "Somerset",
            "Staffordshire",
            "Suffolk",
            "Surrey",
            "Sussex",
            "Warwickshire",
            "Westmoreland",
            "Wiltshire",
            "Worcestershire",
            "Yorkshire"
        ],
        "Nocobar Islands": [
            "Antrim",
            "Armagh",
            "Down",
            "Fermanagh",
            "Londonderry",
            "Tyrone"
        ],
        "Andhra Pradesh": [
            "Ayrshire",
            "Borders",
            "Central Scotland",
            "Dumfries and Galloway",
            "Dunbartonshire and Argyll & Bute",
            "Fife",
            "Grampian",
            "Glasgow",
            "Highlands and Western Isles",
            "Lanarkshire",
            "Lothian",
            "Orkney and Shetland",
            "Renfrewshire",
            "Tayside"
        ],
        "Arunachal Pradesh": [
            "Blaenau Gwent",
            "Bridgend",
            "Caerphilly",
            "Cardiff",
            "Carmarthenshire",
            "Ceredigion",
            "Conwy",
            "Denbighshire",
            "Flintshire",
            "Gwynedd",
            " Isle of Anglesey",
            " Merthyr Tydfil",
            "Monmouthshire",
            "Neath Port Talbot",
            "Newport",
            "Pembrokeshire",
            "Powys",
            " Rhondda Cynon Taff",
            " Swansea",
            "Torfaen",
            "Vale of Glamorgan",
            "Wrexham"
        ],
        "Assam": [
            "Islamabad"
        ],
        "Bihar": [
            "Others"
        ],
        "Chandigarh": [
            "Abhantur",
            "Ambikapur",
            "Balodabazar",
            "Bastar",
            "Bhatapara",
            "Bhilai",
            "Bilaspur",
            "Champa",
            "Dachdri",
            "Dantewada",
            "Delhirajghara",
            "Dhamtari",
            "Dongargarh",
            "Gewra",
            "Hirmi",
            "Jagdalpur",
            "Jangir",
            "Jashpur",
            "Kanker",
            "Kawardha",
            "Kharsiya",
            "Kheragam",
            "Korba",
            "Koria",
            "Kundagaon",
            "Kusham",
            "Mahasamund",
            "Manendragarh",
            "Raibagh",
            "Raigarh",
            "Raipur",
            "Rawan",
            "Sarguja",
            "Shakti",
            "Singma",
            "Tedesa",
            "Tikamgarh",
            "Uthal"
        ],
        "Delhi": [
            "Delhi"
        ],
        "Goa": [
            "Amona",
            "Kaija",
            "Kankali",
            "Karwar",
            "Kudal",
            "Malvan",
            "Margoa",
            "Molen",
            "Panaji",
            "Panjim",
            "Pernem",
            "Ponda",
            "Savardem",
            "Sawantwadi",
            "Sioli",
            "Vengurla",
            "Verna"
        ],
        "Gujarat": [
            "Acchad",
            "Adhewada",
            "Adityanagar",
            "Ahmedabad",
            "Ahuva",
            "Ahwa Dang",
            "Alang",
            "Amboli",
            "Amletha",
            "Amod",
            "Amreli",
            "Amroli",
            "Anand",
            "Ankhi",
            "Ankleshwar",
            "Aslali",
            "Athal",
            "Babara",
            "Bahucharaji",
            "Balal",
            "Balasinor",
            "Bamanbor",
            "Bardoli",
            "Baroda",
            "Batad",
            "Batva",
            "Bayad",
            "Bhat",
            "Bhavnagar",
            "Bharuch",
            "Bhilka",
            "Bhuj-Kutch",
            "Bilimora",
            "Budhel",
            "Chalthan",
            "Chanchvel",
            "Chansama",
            "Charavada",
            "Charoti",
            "Chavand",
            "Chhataral",
            "Chikli",
            "Chinchpada",
            "Chorwad",
            "Chotila",
            "Dahegaom",
            "Dahej",
            "Dahod",
            "Dalpur",
            "Daman",
            "Dantiwada",
            "Dapada",
            "Deesa",
            "Dehgam",
            "Dhandkuwa",
            "Dharangandhra",
            "Dharanpur",
            "Dharr",
            "Dhola",
            "Dholka",
            "Dhoraji",
            "Dhroli",
            "Dissa",
            "Diu",
            "Dujha",
            "Dumas",
            "Dungri",
            "Dwaraka",
            "Gadada",
            "Gajera",
            "Gandhar",
            "Gandhidham",
            "Gandhinagar",
            "Gangadhara",
            "Godhra",
            "Gondal",
            "Halol",
            "Halvad",
            "Harij",
            "Hazira",
            "Himmatnagar",
            "Ichhapore",
            "Idar",
            "Jambusar",
            "Jam Khambhalia",
            "Jamnagar",
            "Jamsalaya",
            "Jamvanthli",
            "Jhalod",
            "Junagadh",
            "Kadodara",
            "Kakrapar",
            "Kalatalav",
            "Kalol(Pachamahal)",
            "Kalyanpura",
            "Kamrej",
            "Kansari",
            "Kapadwanj",
            "Karanj",
            "Karjan",
            "Kawas",
            "Keshod",
            "Kevadia Colony",
            "Khadoli",
            "Khambat",
            "Khanvel",
            "Kharach",
            "Kheda",
            "Kheralu",
            "Khutli",
            "Kim",
            "Kodinar",
            "Kosambha",
            "Kovaya",
            "Kribhco Nagar",
            "Kurshad",
            "Kutiyana",
            "Lakthar",
            "Lalpur",
            "Laskana",
            "Lathi",
            "Limbadi",
            "Limbarsi",
            "Limdi",
            "Lukhatar",
            "Lunawala",
            "Madra",
            "Magdalla",
            "Magob",
            "Mahuva",
            "Malia",
            "Mamsa",
            "Manavadar",
            "Mandvi",
            "Mangrol",
            "Mansa",
            "Maroli",
            "Mehsana",
            "Mithapur",
            "Miyagam",
            "Modasa",
            "Morbi",
            "Motaborasara (Tal)",
            "Muli",
            "Nadiad",
            "Naninaroli",
            "Nasvadi",
            "Navipur",
            "Navsari",
            "Netrang",
            "Okha",
            "Olpad",
            "ONGC Colony",
            "Padra",
            "Paddhari",
            "Palanpur",
            "Palej",
            "Palitana",
            "Palsana",
            "Patadi",
            "Patan",
            "Phalasana",
            "Pipavav",
            "Porbandar",
            "Pranjit",
            "Radhapur",
            "Rajkot",
            "Rajpipla",
            "Rajula",
            "Rakanpur",
            "Rakholi",
            "Ranpur",
            "Sachin",
            "Saili",
            "Sami(BIF-Radhanpur)",
            "Sankhede",
            "Santrampur",
            "Sarkhej",
            "Saroli",
            "Savali",
            "Savarkundla",
            "Sayala",
            "Sayan",
            "Shehra",
            "Shikka",
            "Sidhapur",
            "Sihor",
            "Silvassa Town",
            "Sinor",
            "Songadh (Vyara)",
            "Surangi",
            "Surat",
            "Surendranagar",
            "Sutrapada",
            "Tagdi",
            "Talaja",
            "Talasari",
            "Tansa",
            "Tharad",
            "Thol",
            "Tinpatiya",
            "Uchhad",
            "Ukai",
            "Umalla",
            "Umbergaon",
            "Umerkai",
            "Una",
            "Unjha",
            "Upleta",
            "Usrang",
            "Vadnagar",
            "Vagra",
            "Valbhipur",
            "Vallabh Vidhyanagar",
            "Valsad",
            "Vapi",
            "Verawal",
            "Vijapur",
            "Viramgam",
            "Virpur",
            "Visavadar",
            "Visnagar",
            "Viyra",
            "Waghodia",
            "Zafrabad",
            "Zanor"
        ],
        "Haryana": [
            "Adampur",
            "Agroha",
            "Ambala Cantt.",
            "Bahadurgarh",
            "Bahal",
            "Barwala",
            "Bawal",
            "Bhakhri",
            "Bhiwani",
            "Charkhidadri",
            "Dharuhera",
            "Faridabad",
            "Fatehabad",
            "Ghatal",
            "Gohana",
            "Gurgaon   ",
            "Hansi",
            "Hissar",
            "Hodal",
            "Jaliawas",
            "Jhajjar",
            "Jind",
            "Karnal",
            "Kaithal",
            "Kalawani",
            "Khuskhira",
            "Kosli",
            "Kurukshetra",
            "Masani",
            "Mohinder Gargh",
            "Narayangarh",
            "Narnaul",
            "Narnod",
            "Narwana",
            "Nimrana",
            "Panchkula",
            "Palwal",
            "Panipat",
            "Pataudi",
            "Piyala",
            "Rajpura",
            "Rewari",
            "Rohtak",
            "Sangwari",
            "Shahbad",
            "Shahjanpur",
            "Sirsa",
            "Siswala",
            "Siwani",
            "Sohna",
            "Sonepat",
            "Tauru",
            "Tijara",
            "Tohana"
        ],
        "Himachal Pradesh": [
            "Baddi",
            "Bilaspur",
            "Chappercheri",
            "Dagshai",
            "Darlakat",
            "Dharamsala",
            "Joginder Nagar",
            "Kasauli",
            "Kullu",
            "Kurali",
            "Manali",
            "Mandi",
            "Nalagarh",
            "Nangal",
            "Palampur",
            "Parwanoo",
            "Rudrapur",
            "Shimla",
            "Soghi",
            "Solan"
        ],
        "Jammu & Kashmir": [
            "Anantnag",
            "Akhnoor",
            "Baramulla",
            "B D Wari",
            "Dooda",
            "Hawal",
            "Jammu",
            "Kathua",
            "Katra",
            "Kishanpur",
            "Kupwara",
            "Poonch",
            "Pulwama",
            "Rajouri",
            "R S Pura",
            "Samba",
            "Srinagar",
            "Sopore",
            "Udampur"
        ],
        "Jharkhand": [
            "Adityapur",
            "Bokaro",
            "Chaibasa",
            "Chakradarpur",
            "Chand Colony",
            "Chandil",
            "Chasnala",
            "Daltanganj",
            "Deoghar",
            "Dhanbad",
            "Dumka",
            "Ghatsila",
            "Giridhi",
            "Godda",
            "Gomah",
            "Gomia",
            "Gumla",
            "Hazaribagh",
            "Jadugoda",
            "Jamshedpur",
            "Jharia",
            "Jugsalai",
            "Kadma",
            "Lohardarga",
            "Muri",
            "Palamau",
            "Panposeh",
            "Ranchi",
            "Sindri",
            "Soonari",
            "Tenughat"
        ],
        "Karnataka": [
            "Alaguru",
            "Alur",
            "Ammasandra",
            "Amritnagar",
            "Ankola",
            "Arkalgud",
            "Arsikere",
            "Athani",
            "Badami",
            "Bagalkot",
            "Bailhongal",
            "Balehonnur",
            "Balur",
            "Bangalore",
            "Banhatti",
            "Bannur",
            "Bantwal",
            "Basaralu",
            "Batkal",
            "Bedgi",
            "Belgaum",
            "Bellary",
            "Bellur",
            "Belthangady",
            "Bhadravathi",
            "Bhalki",
            "Bidadi",
            "Bidar",
            "Bijapur",
            "Birur",
            "Bommanahal",
            "Byadagi",
            "Chakara",
            "Challakere",
            "Chamrajnagar",
            "Chanaripatna",
            "Channagiri",
            "Channapatana",
            "Chickballapur",
            "Chikmangalur",
            "Chikodi",
            "Chintamani",
            "Chitradurga",
            "C R Patnam",
            "Dandeli",
            "Darmastala",
            "Davanagere",
            "Devengunthui",
            "Dodballapur",
            "Dukkavati",
            "Farangipet",
            "Gadag",
            "Gajendragad",
            "Gangavati",
            "Gerusoppa",
            "Gokak",
            "Goni Koppa",
            "Gundalpet",
            "Gulbarga",
            "Halebalur",
            "Halial",
            "Hanagal",
            "Harihar",
            "Harpahalli",
            "Hasadurga",
            "Hassan",
            "Haveri",
            "H D Kote",
            "Hebri",
            "Hirekerur",
            "Holakere",
            "Holenarsinghpor",
            "Holkotti",
            "Honnalli",
            "Honnavar",
            "Hosanagar",
            "Hosangadi",
            "Hoskote",
            "Hospet",
            "Hubli",
            "Hukkeri",
            "Humnabad",
            "Hunsur",
            "Ilkal",
            "Jaglur",
            "Jamkhandi",
            "Jigani",
            "Jog Falls",
            "Kadur",
            "Kaganala",
            "Kallegala",
            "Kampli",
            "Kanekal",
            "Kargal",
            "Karkala",
            "Karwar",
            "Kaup",
            "Khanapur",
            "Khanpur",
            "Kinnigoli",
            "Kittur",
            "K M Doddi",
            "Kolar (KGF)",
            "Kollegal",
            "Konaje",
            "Koppal",
            "Kotaswara",
            "Kottur",
            "K R Nagar",
            "K R Pet",
            "Kudligi",
            "Kudremuk",
            "Kumalgodre",
            "Kumta",
            "Kundapur",
            "Kunigal",
            "Kurugodu",
            "Kushalnagar",
            "Kustagi",
            "Lingasugur",
            "Lokapur",
            "Maddur",
            "Madhugiri",
            "Madikeri",
            "Coorg",
            "Majeshwar",
            "Malakalmur",
            "Malavally",
            "Malingapur",
            "Malur",
            "Manavi",
            "Mandya ",
            "Mangalore",
            "Manipal",
            "Mantralayam",
            "Manvi",
            "Masthikatte",
            "Matur",
            "Moodbidri",
            "Muddebihal",
            "Mudhol",
            "Mulbagal",
            "Mulki",
            "Mundgod",
            "Mysore",
            "Nagamangala",
            "Nanjangud",
            "Nargundh",
            "Neeleshwar",
            "Nitte",
            "Oppinangadi",
            "Padubidhri",
            "Paiyanur",
            "Pandavapura",
            "Panemangalore",
            "Peenya",
            "Piriya Pattna",
            "Ponnmpet",
            "Puttur",
            "Raichur",
            "Ramanagaram",
            "Ramdurg",
            "Ramnagar",
            "Rampura",
            "Rayadurga",
            "Ron",
            "Sagar",
            "Sandur",
            "Sankleshwar",
            "Saundatti",
            "Shakleshpura",
            "Shaktinagar",
            "Shiggon",
            "Shikaripura",
            "Shimoga",
            "Siddapura",
            "Siddelgutta",
            "Sindhanoor",
            "Sira",
            "Sirigeri",
            "Sirsi",
            "Siruguppa",
            "Soraba",
            "Srinivaspur",
            "Sri Rangapatnam",
            "Subramanya",
            "Sulia",
            "T. Narasipur",
            "Taaguppa",
            "Tarikere",
            "Thirthanhalli",
            "Tiptur",
            "Toranagallu",
            "Tumkur",
            "Udupi",
            "Ugaarkurg",
            "Ujire",
            "Ullal",
            "Uravakonda",
            "Virajpet",
            "Yellapur"
        ],
        "Kerala": [
            "Aanachal",
            "Aanakkayam",
            "Adoor",
            "Alathur",
            "Allakode",
            "Alleppey",
            "Alwaye",
            "Amritapuri",
            "Angamally",
            "Ativaram",
            "Attingal",
            "Bilathra",
            "Calicut",
            "Cannanore",
            "Chaeavakad",
            "Challakudy",
            "Changanassery",
            "Cheerupuza",
            "Chelari",
            "Chellamdara",
            "Chembery",
            "Chemmad",
            "Chenthalod",
            "Cherpulasery",
            "Chittur",
            "Cochin",
            "Edakara",
            "Edappal",
            "Eddapalli",
            "Erikode",
            "Ernakulam",
            "Gopalapuram",
            "Guruvayyur",
            "Hosdurg",
            "Idukki",
            "Iringalakuba",
            "Iritty",
            "Kadalur",
            "Kaladi",
            "Kalikavu",
            "Kalladikode",
            "Kalpagancherry",
            "Kalpetta",
            "Kanhangadu",
            "Kaniambadi",
            "Kanjirapally",
            "Kannur",
            "Karuppode",
            "Karuvaraundu",
            "Kasargode",
            "Koduvayyur",
            "Kolencheri",
            "Kollam",
            "Kollengode",
            "Konduty",
            "Kongad",
            "Koothupuarambu",
            "Koothupuzha",
            "Koppam",
            "Kotarakkara",
            "Kottakal",
            "Kottayam",
            "Kozhikode",
            "Krishnapuram",
            "Kumali",
            "Kumuli",
            "Kundava Quilon",
            "Kunnalur",
            "Kunnamkulam",
            "Kuthautuparambh",
            "Kuthupuzha",
            "Kuttanad",
            "Kuttipuram",
            "LPSC/PSLV(VSSC)",
            "Mahe",
            "Mala",
            "Malappuram",
            "Malampuzha",
            "Malayattur",
            "Mallapuram",
            "Mambudu",
            "Manarkadi",
            "Manathavadi",
            "Manjeri",
            "Mattankur",
            "Meenakshipuram",
            "Meenangadi",
            "Mukkom (Reg.Engg)",
            "Munnar",
            "Muvattupuzha",
            "Nadapuram",
            "Nelambur",
            "Nelesuaram",
            "Nenmara",
            "Oachira",
            "Olavakode",
            "Orkatteri",
            "Ottapalam",
            "Painavu",
            "Pala",
            "Palghat",
            "Pallasana",
            "Pallur",
            "Palucherry",
            "Paranur",
            "Parappanagadi",
            "Paripally",
            "Pariyaram",
            "Pathanamthitta",
            "Pathanapuram",
            "Pattambi",
            "Payyanore",
            "Pazayangadi",
            "Perambra",
            "Peravoor",
            "Perpanangadi",
            "Perumbavoor",
            "Pilathara",
            "Ponnani",
            "Pulikal",
            "Punalur",
            "Puthunagaram",
            "Quilon (Kollam)",
            "Ramanattukara",
            "Shornur",
            "Sultanbatterry",
            "Tannur",
            "Tellicherry",
            "Teravur",
            "Thalassery",
            "Thaliparambu",
            "Thamaraacary",
            "Thekkadi",
            "Thirunnavaya",
            "Thiruvalla",
            "Thodupuzha",
            "Thriprayar",
            "Tirur",
            "Tiruvarangadi",
            "Trichur (Thrissur)",
            "Thiruvananthapuram",
            "Vadakara",
            "Vadakkanchery",
            "Vaikom",
            "Vallancherry",
            "Vandiperiyar",
            "Vandour",
            "Varkala",
            "Vazhikadvu",
            "Vemballur",
            "Vyhiri"
        ],
        "Madhya Pradesh": [
            "Amla",
            "Amlori",
            "Babai",
            "Badwah",
            "Bairasia",
            "Banmore",
            "Bareli",
            "Barwabu",
            "Beena",
            "Begumganj",
            "Betul",
            "Bhaishdehi",
            "Bhind",
            "Bhitoni",
            "Bhopal",
            "Bhuanpur",
            "Bhuri Bakania",
            "Budhni",
            "Burhanpur",
            "Chattarpur",
            "Chindara",
            "Chitrakoot",
            "Dabra",
            "Damoh",
            "Datia",
            "Deewanganj",
            "Dewas",
            "Dhamnod",
            "Dhar",
            "Dindori",
            "Gadarwada",
            "Gandhinagar",
            "Ganjbasoda",
            "Ghatabillode",
            "Gotegaon",
            "Guna",
            "Guna",
            "Gwalior",
            "Harda",
            "Hoshangabad",
            "Indore",
            "Itarsi",
            "Jabalpur",
            "Jadra",
            "Jayant",
            "Jhabua",
            "Katni",
            "Kaymore",
            "Khajuraho",
            "Khandwa",
            "Khargone",
            "Khor",
            "Maihar",
            "Manasa",
            "Mandla",
            "Mandsaur",
            "Mandideep",
            "Morena",
            "Nagda",
            "Narasinghgarh",
            "Narsinghpur",
            "Neemuch (Ratlam)",
            "Nepanagar",
            "Obedullaganj",
            "Panchmarhi",
            "Panna",
            "Pigdaber",
            "Pipariya",
            "Piplya Mandi",
            "Pithampur",
            "Rairu",
            "Raisen",
            "Rajgarh",
            "Rau",
            "Rewa",
            "Sagar",
            "Sagar",
            "Sailana",
            "Salamatpur",
            "Sanchi",
            "Sarni",
            "Sarver Village",
            "Satna",
            "Sehat Ganj",
            "Sehore",
            "Seoni",
            "Seopurkala",
            "Shadol",
            "Shajapur",
            "Sheopur",
            "Shivpuri",
            "Shivpuri",
            "Siddhi",
            "Sihora",
            "Singroli",
            "Sitamau",
            "Tekanpur",
            "Udaipura",
            "Ujjain",
            "Umaria",
            "Vidisha",
            "Vijaypur (NFL)",
            "Vindhyanagar",
            "Waidhan"
        ],
        "Maharashtra": [
            "Agashi",
            "Ahmednagar",
            "Akola",
            "Akolner",
            "Alibaug",
            "Amalner",
            "Ambajogai",
            "Ambernath",
            "Amravati",
            "Amreli",
            "Arnala",
            "Asangaon",
            "Atit",
            "Aurangabad",
            "Bableshwar",
            "Badlapur",
            "Balaghat",
            "Baramati",
            "Beed",
            "Bhagur",
            "Bhalgad",
            "Bhandara",
            "Bhandardara",
            "Bhigaon",
            "Bhiwandi",
            "Bhootbungalo",
            "Bhor",
            "Bhunj",
            "Bhusawal",
            "Buldhana",
            "Butibori",
            "Chakan",
            "Chalisgaon",
            "Chandrapur",
            "Chindwara",
            "Chiplun",
            "Chopda",
            "Dahiwadi",
            "Dandacha",
            "Daund",
            "Devlalicamp",
            "Dhamadse",
            "Dhanu",
            "Dhebewadi",
            "Dhule",
            "Dindori",
            "Dolvirevanda",
            "Dombivilli",
            "Dronagiri",
            "Gadchiroli",
            "Ganeshpuri",
            "Gondia",
            "Guhagar",
            "Hatkadangle",
            "Ichalkaranji",
            "Igatpuri",
            "Indapur",
            "Islampur",
            "Jaisingpur",
            "Jalgaon",
            "Jalna",
            "Jamkhed",
            "Jamner",
            "Jejuri",
            "Jintur",
            "JNPT",
            "Junnar",
            "Kadoli",
            "Kagal",
            "Kaman",
            "Karad",
            "Karanja",
            "Karjat",
            "Kedegaon",
            "Khamgaon",
            "Khapoli",
            "Khed",
            "Kirloskarwadi",
            "Kolhapur",
            "Kone",
            "Kopergaon",
            "Koregaon",
            "Kurkumbh",
            "Kushire",
            "Kothrud(Pune)",
            "Lanja",
            "Latur",
            "Lonand",
            "Lonavala",
            "Loni",
            "Mahableshwar",
            "Mahad",
            "Malegaon",
            "Malhapur",
            "Manchar",
            "Manmad",
            "Maval",
            "Medha",
            "Megharaj",
            "Miraj",
            "Mira Road",
            "Muktai",
            "Mumbai",
            "Mumbai - Vasai",
            "Murbad",
            "Nagpur",
            "Nanded",
            "Nandurbar",
            "Narayangaon",
            "Nasik",
            "Navi Mumbai",
            "Newasa",
            "Nipani",
            "Nira",
            "Nursapur",
            "Oglewadi",
            "Osmanabad",
            "Pachora",
            "Paithan",
            "Palhat",
            "Palolem",
            "Panchgani",
            "Panvel",
            "Paralivaijanath",
            "Parbhani",
            "Parner",
            "Pathardi",
            "Pen",
            "Persure",
            "Phaltan",
            "Pimpri And Chinchwad",
            "Plaspe",
            "Pune",
            "Pusad",
            "Pusegaon",
            "Rabale",
            "Radhangai",
            "Rahate",
            "Rahuri",
            "Rajapur",
            "Rajgurunagar",
            "Ratnagiri",
            "Raver",
            "Roha",
            "Safale",
            "Sahapur",
            "Sangamner",
            "Sangli",
            "Satara",
            "Shadad",
            "Shahapur",
            "Shamalji",
            "Shindewadi",
            "Shirdi",
            "Shirpur",
            "Shirur",
            "Shirval",
            "Sholapur",
            "Shrirampur",
            "Sinddurg",
            "Sinnar",
            "Solapur",
            "Srigonda",
            "Structer Urban",
            "Talegaon",
            "Tarapur",
            "Tasgaon",
            "Thal",
            "Thane",
            "Tisery",
            "Tumsar",
            "Ulhasnagar",
            "Urse",
            "Uthan",
            "Utran",
            "Vaduj",
            "Vajreshwari",
            "Vambori",
            "Vani",
            "Vitthalwadi",
            "Vashi",
            "Wachandnagar",
            "Wada",
            "Wadgaon Budruk",
            "Wadiware",
            "Wai",
            "Waluj",
            "Warangaon",
            "Wardha",
            "Washim",
            "Yadrav",
            "Yeotmal",
            "Zagalwadi"
        ],
        "Manipur": [
            "Bishnupur",
            "Chandel",
            "Churanchandpur",
            "Imphal",
            "Manipur University",
            "Senapati",
            "Temenglong",
            "Thobl",
            "Ukhrul"
        ],
        "Meghalaya": [
            "Jowai",
            "Nongstoin",
            "Shillong",
            "Tura"
        ],
        "Mizoram": [
            "Lunglei",
            "Aizwal"
        ],
        "Nagaland": [
            "Dimapur",
            "Kohima",
            "Mankochung",
            "Mokak Chung",
            "Mon",
            "Phek",
            "Tuensang",
            "Wokha",
            "Zunheboto"
        ],
        "New Delhi": [
            "New Delhi"
        ],
        "Orissa": [
            "Anugul",
            "Balangir",
            "Balasore",
            "Bargarh",
            "Baripada",
            "Barpalli",
            "Behrampur",
            "Bhavanipatna",
            "Bhubaneshwar",
            "Brajraj Nagar",
            "Chatrapur",
            "Cuttack",
            "Damanjodi",
            "Delpahar",
            "Dhenkanal",
            "Gajapati",
            "Gopalpur",
            "Jharsuguda",
            "Jora",
            "Kanisi",
            "Keonjhar",
            "Khurdha",
            "Khurdha",
            "Koraput",
            "Malkangiri",
            "Navapatnam",
            "Nayagarh",
            "Paradeep",
            "Phulbani",
            "Puri",
            "Rayagada",
            "Rourkela",
            "Sambalpur"
        ],
        "Pondicherry": [
            "Aurofood",
            "Courivinatha",
            "Kallambakkam",
            "Maduraipakkam",
            "Marakkanam",
            "Nellekuppam",
            "Nettapakkam",
            "Pakkam",
            "Pondicherry",
            "Sellipattu",
            "Surapattu",
            "Thimmapap",
            "Thirukollur",
            "Thirumangala",
            "Valavanur",
            "Viranam",
            "Yanam"
        ],
        "Punjab": [
            "Abohar",
            "Alipur",
            "Amritsar",
            "Banga",
            "Barnala",
            "Batala",
            "Bhatinda",
            "Bhandla",
            "Biyas",
            "Chanhal",
            "Chauhal",
            "Damtal",
            "Firozpur",
            "Goraya",
            "Govindwal Sahib",
            "Gurdaspur",
            "Hamira",
            "Hanmara",
            "Hoshiarpur",
            "Jagraon",
            "Jallandhar",
            "Johal",
            "Kapurthala",
            "Khanna",
            "Khasha",
            "Komara",
            "Kotkapura",
            "Lalru",
            "Ludhiana",
            "Malerkotia",
            "Mandi Govindgarh",
            "Moga",
            "Mohali",
            "Nakodar",
            "Nayamansal",
            "Naya Nangal",
            "Patiala",
            "Pathankot",
            "Phagwara",
            "Pontassahib",
            "Ropar",
            "Samrala",
            "Sangrur",
            "Shapurkandi",
            "Tanda",
            "Taran Taran"
        ],
        "Rajasthan": [
            "Agucha (Mince)",
            "Ajmer",
            "Alwar",
            "Anupgadh",
            "Anuskakti",
            "Balotra",
            "Banswara",
            "Baren",
            "Barmer",
            "Beawar",
            "Bharatpur",
            "Bhavani Mandi",
            "Bhilwara",
            "Bhiwadi",
            "Bhopalgarh",
            "Bijaynagar",
            "Bikaner",
            "Chakcho",
            "Chaksu",
            "Chittorgarh",
            "Churu",
            "Dabok",
            "Dausa",
            "Delwada",
            "Dholpur",
            "Dungarpur",
            "Fathenagar",
            "Firozpur",
            "Gadepan",
            "Gangapur City",
            "Ganwana",
            "Gotan",
            "Gudli",
            "Gulabpura",
            "Guraisar",
            "Jaipur",
            "Jaisalmer",
            "Jaisamand",
            "Jetaran",
            "Jetpur",
            "Jhalawar",
            "Jhalore",
            "Jhunjhunu",
            "Jodhpur",
            "Kakroli",
            "Kalayant",
            "Kapasan",
            "Karaikh Nagar",
            "Kekri",
            "Kherwada",
            "Khetri Nagar",
            "Kishangarh",
            "Kota",
            "Lakheri",
            "Lunkaransar",
            "Mahthaniya",
            "Mangaliyavas",
            "Mauvur",
            "Merta City",
            "Mount Abu/Abu Road",
            "Nagor",
            "Nasirabad",
            "Nathdawara",
            "Neem Ka Thana",
            "Nimbhera",
            "Niwai",
            "Nokha",
            "Pali",
            "Pilani",
            "Pokhran",
            "Pushkar",
            "Raila",
            "Rajsaman D",
            "Ramganj Mandi",
            "Ranathambhor",
            "Ratan Gadh",
            "Ravla",
            "Rawatbhata",
            "Rishabhdev",
            "Santpur",
            "Sapivalla",
            "Sardar Sahar",
            "Sarika",
            "Sawai Madhopur",
            "Shahjhapur",
            "Shivganj",
            "Sikar",
            "Sirdhi",
            "Sojat City",
            "Sriganganagar",
            "Sujaan Gadh",
            "Sumerpur",
            "Surat Garh",
            "Tara Nagar",
            "Udaipur",
            "Vijaynagar"
        ],
        "Sikkim": [
            "Bardhang",
            "Gangtok",
            "Jorthan",
            "Malli",
            "Mangan",
            "Namchi",
            "Palling",
            "Rangit Nagar",
            "Rangpo"
        ],
        "Tamilnadu": [
            "Alangulam",
            "Algaiyamandapam",
            "Ambasamudram",
            "Ambasamudram",
            "Ambur",
            "Ammaipakkam",
            "Ammapet",
            "Annur",
            "Arakonam",
            "Arambakkam",
            "Aranthangi",
            "Aravai Mozhili",
            "Aravakurchi",
            "Arcot",
            "Aripakkam",
            "Ariyalur",
            "Arumuganeri",
            "Arunavoyal",
            "Aruppukottai",
            "Athipet",
            "Athur",
            "Attur",
            "Avanashi",
            "Avinashi",
            "Bahoor",
            "Batalagundu",
            "Berigai",
            "Bhavani",
            "Burgoor",
            "Cheiyyar",
            "Chendurai",
            "Chengalpattu",
            "Chenjee",
            "Chennai",
            "Chennaimalai",
            "Chidambaram",
            "Chinnamanur",
            "Chinnasalem",
            "Chitteri",
            "Coimbatore",
            "Coonoor",
            "Covelong Beach",
            "Cudalur",
            "Cuddalore",
            "Cumbam",
            "Dalmiyapuram",
            "Denkanikottai",
            "Devakottai",
            "Devampattu",
            "Devaram",
            "D Gudalur",
            "Dharapuram",
            "Dharmapuri",
            "Dindigal",
            "Dindigul",
            "Edapadi",
            "Elampillai",
            "Elayirampannai",
            "Ellavoyalchavadi",
            "Erode",
            "Erwadi",
            "Ettayapuram",
            "Gobichettipalayam",
            "Gourivakkam",
            "Gudiyyatam",
            "Gujiliamparai",
            "Gummidipoondi",
            "Harur",
            "Hosur",
            "Injampakkam",
            "Irrugattukottai",
            "Jadapalyam",
            "Jayamkondam",
            "Kabilasthala",
            "Kagithapuram",
            "Kakaveli",
            "Kakkalpur",
            "Kalavalapalem",
            "Kalladi Patty",
            "Kallakadu",
            "Kalliurani",
            "Kalpakkam",
            "Kamantholi",
            "Kambam",
            "Kancheepuram",
            "Kanchipuram",
            "Kandigai",
            "Kangayam",
            "Kaniyakavilai",
            "Kanniyakumari",
            "Kanyakumari",
            "Karadivavi",
            "Karaikal",
            "Karaikudi",
            "Kariamangalam",
            "Karur",
            "Katpadi",
            "Kaveripatnam",
            "Kavundapadi",
            "Kayalpatnam",
            "Kayalpattinam",
            "Kayatharu",
            "Kelamangalam",
            "Kelambakkam",
            "Kelmangala",
            "Kilakkarai",
            "Kodaikanal",
            "Kodaikannal",
            "Kodai Road",
            "Kollamangudi",
            "Komarapalayam",
            "Kotagiri",
            "Kovalam",
            "Kovilpatti",
            "Krishnagiri",
            "Krishnan Koil",
            "K R Thoppur",
            "Kudankulam",
            "Kudapakkam",
            "Kudumudi",
            "Kulachal",
            "Kulasekaram",
            "Kulithalai",
            "Kumaramangalam",
            "Kumbakonam",
            "Kunnathur",
            "Kuppuswamypuram",
            "Kurupur",
            "Lalgudi",
            "Madhuranthakam",
            "Madurai",
            "Maduravoyal",
            "Mahadanapuram",
            "Mailatthurai",
            "Mamallapuram",
            "Mamandur",
            "Mamsapuram",
            "Manapadu",
            "Manaparai",
            "Mannarkudi",
            "Maraimala Nagar",
            "Marthandam",
            "Marthandam",
            "Mayanoor",
            "Mayuram",
            "Melmaruvattur",
            "Mettupalayam",
            "Mettur",
            "Minjur",
            "Mohan Nagar",
            "Monday market",
            "Mudukalathur",
            "Musuri",
            "Myiladuthurai",
            "Nagapattinam",
            "Nagercoil",
            "Namakkal",
            "Nanguneri",
            "Nasarathu",
            "Nattam",
            "Nazareth",
            "Neyveli",
            "Oddanchatram",
            "Omalur",
            "Ooty",
            "Ottapidaram",
            "Palani",
            "Palani",
            "Palayam",
            "Palladham",
            "Pallagondapalam",
            "Pallapathi",
            "Panruti",
            "Panthalkudi",
            "Pappanasam",
            "Paramakudi",
            "Paramathivelur",
            "Pattbhiram",
            "Pattukottai",
            "Perandurai (Sipcot)",
            "Periyakulam",
            "Perumanallur",
            "Pettaivaithalai",
            "Pochampally",
            "Pollachi",
            "Polur",
            "Poompuhar",
            "Poonnamallee ",
            "Potteneri",
            "Pudukottai",
            "Pukkathurai",
            "Pulivalam",
            "Puliyampatti",
            "Purandurai",
            "Rajapalayam",
            "Rajapalayam",
            "Ramachandrapuram",
            "Ramachandrapuram",
            "Ramanad",
            "Ramanand",
            "Ramasamy Raja Nagar",
            "Rameshwaram",
            "Rameswaram",
            "Ramnathpuram",
            "Ranipet",
            "Rasipuram",
            "Reddiyapatti",
            "Roykotta",
            "Sakthinagar",
            "Salem",
            "Sankarankoil",
            "Sankarankoil",
            "Sathankulam",
            "Sathur",
            "Sathyamangala",
            "Sengottai",
            "Sengottai",
            "Seranmadevi",
            "Shanthmangalam",
            "Sholinganallur",
            "Sholinger",
            "Sirumugai",
            "Sivadhapuram",
            "Sivagangai",
            "Sivakasi",
            "Somannur",
            "Soolagiri",
            "Sriperumbudur",
            "Srivilliputhur",
            "Sultanpet",
            "Sunguvarchatram",
            "Tanjore (Thanjavur)",
            "Thakkalai",
            "Thalavaipuram",
            "Tharagamapatti",
            "Theivasayal Puram",
            "Thekkampatty",
            "Theni",
            "Thenkasi",
            "Thenkasi",
            "Thennilai",
            "Thirubuvani",
            "Thiruchendur",
            "Thirukannur",
            "Thirukazhikundram",
            "Thirumazhisai",
            "Thirunindravur",
            "Thiruvallur",
            "Thiruvannamalai",
            "Thiruvarur",
            "Tindivanam",
            "Tiruchendur",
            "Tiruchengode",
            "Tirunelveli",
            "Tirupathur",
            "Tiruporur",
            "Tiruppur",
            "Tiruthanni",
            "Trichy",
            "Tuticorin",
            "Udangudi",
            "Udumalapet",
            "Usilampatti",
            "Uthamapalayam",
            "Uthiramerur",
            "Uthukottai",
            "Utukulai",
            "Vadalur",
            "Vaigam dam",
            "Vakkankulam",
            "Valapadi",
            "Valliyur",
            "Valparai",
            "Vandavasi",
            "Vaniyambadi",
            "Varusanadu",
            "Vedachandur",
            "Vedanthangal",
            "Vedasandur",
            "Vellakkovil",
            "Vellore",
            "Velyathampalam",
            "Vembur",
            "Vijayamangalam",
            "Vilathikulam",
            "Villipuram",
            "Virudhachalam",
            "Virudhunagar",
            "Virudhunagar",
            "Walajahpet",
            "Yercaud"
        ],
        "Tripura": [
            "Agartala"
        ],
        "Uttaranchal": [
            "Dehradun",
            "Doiwala",
            "Haridwar",
            "Joshimath",
            "Kotdwar",
            "Mangalore",
            "Mussoori",
            "Pauri",
            "Rishikesh",
            "Roorkee",
            "Saharanpur",
            "Srinagar",
            "Utharkashi",
            "Vikash Nagar"
        ],
        "Uttar Pradesh": [
            "Agra",
            "Aligarh",
            "Allahabad",
            "Almora",
            "Amala",
            "Amethi",
            "Amroha",
            "Anpara",
            "Avagarh",
            "Azamgarh",
            "Babina",
            "Babrala",
            "Badaun",
            "Bagpat",
            "Bah",
            "Bahadurganj",
            "Ballia",
            "Banda",
            "Bara",
            "Barabanki",
            "Baraut",
            "Bareily",
            "Basti",
            "Bhadohi",
            "Bhimtal",
            "Bijnor",
            "Bilari Tahsil",
            "Bindki Road",
            "Bulandshahar",
            "Chandausi",
            "Chauberpur",
            "Chhata",
            "Chilkana",
            "Chobepur",
            "Chopan",
            "Dadri",
            "Dalla",
            "Daurala",
            "Deoband",
            "Deoria",
            "Dhampur",
            "Dohari Ghat",
            "Etawa",
            "Faizabad",
            "Farah",
            "Farrukabad",
            "Fatehabad",
            "Fathepur",
            "Fathepur Sikri",
            "Firozabad",
            "Gajraula",
            "Gango",
            "Ghaziabad",
            "Ghazipur",
            "Ghoshi",
            "Gonda",
            "Gorakhpur",
            "Haldwani",
            "Hamirpur",
            "Hapur",
            "Harodi",
            "Hastinapur",
            "Hathras",
            "Iglas",
            "Jagdishpur",
            "Jainpur",
            "Jaunpur",
            "Jhansi",
            "Jhansi",
            "Kalpi",
            "Kannauj",
            "Kanpur",
            "Kasganj",
            "Kashimpur",
            "Kasipur",
            "Kathgodam",
            "Kaurva",
            "Kaushambbi",
            "Khairabad",
            "Khatima",
            "Khautali",
            "Khurja",
            "Kopaganj",
            "Korwa",
            "Kosikalan",
            "Lakhimpur(Kheri)",
            "Lalitpur",
            "Lalkunwa",
            "Lohni",
            "Lucknow",
            "Mankapur",
            "Mathura",
            "Maunath Bhanjan",
            "Mawana",
            "Meerut",
            "Mirzapur",
            "Modi Nagar",
            "Mohammadabad",
            "Mohanlalganj",
            "Moradabad",
            "Mubarakpur",
            "Muradnagar",
            "Muzaffarnagar",
            "Najimabad",
            "Nakur",
            "Nanuta",
            "Noida",
            "Noorpur",
            "Obra",
            "Orai",
            "Pata",
            "Phulpur",
            "Pilakuwa",
            "Pilbhit",
            "Pithorgarh",
            "Pratapgrah",
            "Purdel Nagar",
            "Raibareilly",
            "Ramkola",
            "Ramnagar",
            "Rampur",
            "Rania & Jainpur",
            "Raya",
            "Renusagar",
            "Rihandnagar",
            "Robertsganj",
            "Sahibabad",
            "Samshabad",
            "Sanauli",
            "Shahabad",
            "Shahjahanpur",
            "Shakthi Nagar",
            "Shambhal",
            "Shamli",
            "Shikohabad",
            "Sikandra",
            "Sitapur",
            "Sitarganj",
            "Sonabhadra",
            "Sultanpur",
            "Tundala",
            "Unnad",
            "Varanasi",
            "Vidhanagar",
            "Vrindavan",
            "Unnao"
        ],
        "West Bengal": [
            "Alipudwar",
            "Amta",
            "Andal",
            "Arambagh",
            "Aramgarh",
            "Asansol",
            "Ashok Nagar",
            "Athpur",
            "Aurangabad",
            "Bagdogra",
            "Balurghat",
            "Banarhat",
            "Bandel",
            "Bankura",
            "Bansdroni",
            "Barakar",
            "Barasat",
            "Barjora",
            "Barkeshwar",
            "Baswa",
            "Binaguri",
            "Birlapur",
            "Birpara",
            "Birshibpur",
            "Bishnupur",
            "Bolepur",
            "Burdwan",
            "Burnpur",
            "Calcutta",
            "Chandan Nagar",
            "Chinsurah",
            "Chittranjan",
            "Coochbihar",
            "Cooch Behar",
            "Dalkhola",
            "Darjeeling",
            "Deldanga",
            "Dhuliyan",
            "Dhupjuri",
            "Diamond Harbour",
            "Dinahata",
            "Digha",
            "Durgapur",
            "Falta",
            "Falakata",
            "Farakka",
            "Fulia",
            "Ganga Nagar",
            "Gangarampur",
            "Gayeshpur",
            "Ghatla",
            "Habibpur",
            "Habra",
            "Haldibari",
            "Haldia",
            "Haripur",
            "Hasimara",
            "Howrah",
            "Hoyra",
            "Hooghly",
            "Ichapur",
            "Islampur",
            "Jaigon",
            "Jaiganj",
            "Jaldhaka",
            "Jalpaiguri",
            "Jamoria",
            "Jangipur",
            "Jhargram",
            "Junglepur",
            "Kalimpong",
            "Kalna",
            "Kalyani",
            "Kanchanpura",
            "Kandi",
            "Karimpur",
            "Keusiong",
            "Kharagpur",
            "Khargram",
            "Kolaghat",
            "Kolkota",
            "Krishna Nagar",
            "Kuntai",
            "Kurseong",
            "Lalbagh",
            "Lalgola",
            "Makardh",
            "Malbazar",
            "Malda",
            "Mayapur",
            "Maynaguri",
            "Mirzapur",
            "Moinaguri",
            "Mugra",
            "Murshidabad",
            "Nabowip",
            "Nadia",
            "Nagar",
            "Nahijam",
            "Narandrapur",
            "New Barackpore",
            "New Jalpaiguri",
            "Nimari",
            "North 24 Parganas",
            "Palashi",
            "Panagarh",
            "Panchla",
            "Pandeswar",
            "Puruliya",
            "Raghunathganj",
            "Raiganj",
            "Rajpur",
            "Rampurhat",
            "Ranaghat",
            "Raniganj",
            "Ranihati",
            "Raninagar",
            "Ropnarayanpur",
            "Samundargarh",
            "Santipur",
            "Shyam Nagar",
            "Siliguri",
            "Sibmandir",
            "Sonamukhi",
            "Sonpur",
            "South 24 Parganas",
            "Tarkeshwar",
            "Triveni",
            "Ukhara",
            "Ulberia"
        ]
    },
    "Pakistan": {
        "Punjab(pakistan)": [
            "Ahmadpur",
            "Ahmed Nager Chatha",
            "Ali Khan Abad",
            "Alipur",
            "Arifwala",
            "Attock",
            "Bhera",
            "Bhalwal",
            "Bahawalnagar",
            "Bahawalpur",
            "Bhalwal",
            "Bhakkar",
            "Burewala",
            "Chillianwala",
            "Chakwal",
            "Chichawatni",
            "Chiniot",
            "Chishtian",
            "Daska",
            "Darya Khan",
            "Dra Ghazi Khan",
            "Dhaular",
            "Dina",
            "Dinga",
            "Dipalpur",
            "Fateh Jang",
            "Faisalabad",
            "Ghakhar Mandi",
            "Gojra",
            "Gujranwala",
            "Gujrat",
            "Gujar Khan",
            "Hafizabad",
            "Haroonabad",
            "Hasilpur",
            "Haveli Lakha",
            "Jalalpur Jattan",
            "Jampur",
            "Jaranwala",
            "Jauharabad",
            "Jhang",
            "Jhelum",
            "Kalabagh",
            "Karor Lal Esan",
            "Kamalia",
            "K\u00c4moke",
            "Kasur",
            "Khanewal",
            "Khanpur",
            "Kharian",
            "Khushab",
            "Kot Adu",
            "Lahore",
            "Lalamusa",
            "Layyah",
            "Liaquat Pur",
            "Lodhran",
            "Malakwal",
            "Mamoori",
            "Mailsi",
            "Mandi Bahauddin",
            "Mian Channu",
            "Mianwali",
            "Multan",
            "Murree",
            "Muridke",
            "Mianwali Bangla",
            "Muzaffargarh",
            "Narowal",
            "Okara",
            "Renala Khurd",
            "Pakpattan",
            "Pattoki",
            "Pir Mahal",
            "Qaimpur",
            "Qila Didar Singh",
            "Rabwah",
            "Raiwind",
            "Rajanpur",
            "Rahim Yar Khan",
            "Rawalpindi",
            "Sadiqabad",
            "Safdarabad",
            "Sahiwal",
            "Sangla Hill",
            "Sarai Alamgir",
            "Sargodha",
            "Shakargarh",
            "Shekhupura",
            "Sialkot",
            "Sohawa",
            "Soianwala",
            "Siranwali",
            "Talagang",
            "Taxila",
            "Toba Tek Singh",
            "Vehari",
            "Wah Cantonment",
            "Wazirabad"
        ],
        "Sindh": [
            "Badin",
            "Bhirkan",
            "Chak",
            "Dadu",
            "Digri",
            "Diplo",
            "Dokri",
            "Ghotki",
            "Haala",
            "Hyderabad",
            "Islamkot",
            "Jacobabad",
            "Jamshoro",
            "Jungshahi",
            "Kandhkot",
            "Kandiaro",
            "Karachi",
            "Kashmore",
            "Keti Bandar",
            "Khairpur",
            "Kotri",
            "Larkana",
            "Matiari",
            "Mehar",
            "Mirpur Khas",
            "Mithani",
            "Mithi",
            "Mehrabpur",
            "Moro",
            "Nagarparkar",
            "Naudero",
            "Naushahro Feroze",
            "Naushara",
            "Nawabshah",
            "Nawabshah",
            "Nazimabad",
            "Qambar",
            "Qasimabad",
            "Rajo Khanani",
            "Ranipur",
            "Ratodero",
            "Rohri",
            "Sakrand",
            "Sanghar",
            "Shahbandar",
            "Shahdadkot",
            "Shahdadpur",
            "Shahpur Chakar",
            "Shikarpur",
            "Sukkur",
            "Tangwani",
            "Tando Adam",
            "Tando Allahyar",
            "Tando Muhammad Khan",
            "Thatta",
            "Umerkot",
            "Warah"
        ],
        "Khyber Pakhtunkhwa": [
            "Abbottabad",
            "Adezai",
            "Alpuri",
            "Akora Khattak",
            "Ayubia",
            "Banda Daud Shah",
            "Bannu",
            "Batkhela",
            "Battagram",
            "Birote",
            "Chakdara",
            "Charsada",
            "Chitral",
            "Daggar",
            "Dargai",
            "Darya Khan",
            "Dera Ismail Khan",
            "Doaba",
            "Dir",
            "Drosh",
            "Hangu",
            "Haripur",
            "Karak",
            "Kohat",
            "Kulachi",
            "Lakki Marwat",
            "Latamber",
            "Madyan",
            "Mansehra",
            "Mardan",
            "Mastuj",
            "Mingora",
            "Nowshera",
            "Paharpur",
            "Pabbi",
            "Peshawar",
            "Saidu",
            "Sharif",
            "Shorkot",
            "Shewa Adda",
            "Swabi",
            "Tangi",
            "Tank",
            "Thall",
            "Timergara",
            "Tordher"
        ],
        "Balochistan": [
            "Chaman",
            "Dera Murad Jamali",
            "Dera Allah Yar",
            "Gwadar",
            "Hub",
            "Kalat",
            "Kharan",
            "Loralai",
            "Mastung",
            "Nushki",
            "Pasni",
            "Khuzdar",
            "Quetta",
            "Sibi",
            "Turbat",
            "Usta Mohammad",
            "Zhob"
        ],
        "Islamabad": [
            "Islamabad"
        ],
        "Others": [
            "Others"
        ]
    },
    "United States of America": {
        "Alabama": [
            "testing"
        ],
        "Alaska": [],
        "Arizona": [],
        "Arkansas": [],
        "California": [],
        "Colorado": [],
        "Connecticut": [],
        "Delaware": [],
        "Florida": [],
        "Georgia": [],
        "Hawaii": [],
        "Idaho": [],
        "Illinois": [],
        "Indiana": [],
        "Iowa": [],
        "Kansas": [],
        "Kentucky": [],
        "Louisiana": [],
        "Maine": [],
        "Maryland": [],
        "Massachusetts": [],
        "Michigan": [],
        "Minnesota": [],
        "Mississippi": [],
        "Missouri": [],
        "Montana": [],
        "Nebraska": [],
        "Nevada": [],
        "New Hampshire": [],
        "New Jersey": [],
        "New Mexico": [],
        "New York": [],
        "North Carolina": [],
        "North Dakota": [],
        "Ohio": [],
        "Oklahoma": [],
        "Oregon": [],
        "Pennsylvania": [],
        "Rhode Island": [],
        "South Carolina": [],
        "South Dakota": [],
        "Tennessee": [],
        "Texas": [],
        "Utah": [],
        "Vermont": [],
        "Virginia": [],
        "Washington": [],
        "West Virginia": [],
        "Wisconsin": [],
        "Wyoming": [],
        "Others": []
    },
    "United Arab Emirates": {
        "Ajman": [
            "Ajman",
            "Abu Dhabi",
            "Al Fujairah",
            "Al sharjah",
            "Dubai",
            "Ras al khaimah",
            "Umm al Qaiwain"
        ],
        "Abu Dhabi": [],
        "Al Fujairah": [],
        "Al sharjah": [],
        "Dubai": [],
        "Ras al khaimah": [],
        "Umm al Qaiwain": [],
        "Others": []
    },
    "United Kingdom": {
        "England": [
            "Bedfordshire",
            "Berkshire",
            "Buckinghamshire",
            "Cambridgeshire",
            "Cheshire",
            "Cornwall",
            "Cumbria",
            "Derbyshire",
            "Devon",
            "Dorset",
            "Durham",
            "Essex",
            "Gloucestershire",
            "Hampshire",
            "Hertfordshire",
            "Huntingdonshire",
            "Kent",
            "Lancashire",
            "Leicestershire",
            "Lincolnshire",
            "Middlesex",
            "Norfolk",
            "Northamptonshire",
            "Northumberland",
            "Nottinghamshire",
            "Oxfordshire",
            "Rutland",
            "Shropshire",
            "Somerset",
            "Staffordshire",
            "Suffolk",
            "Surrey",
            "Sussex",
            "Warwickshire",
            "Westmoreland",
            "Wiltshire",
            "Worcestershire",
            "Yorkshire"
        ],
        "Northern Ireland": [
            "Antrim",
            "Armagh",
            "Down",
            "Fermanagh",
            "Londonderry",
            "Tyrone"
        ],
        "Scotland": [
            "Ayrshire",
            "Borders",
            "Central Scotland",
            "Dumfries and Galloway",
            "Dunbartonshire and Argyll & Bute",
            "Fife",
            "Grampian",
            "Glasgow",
            "Highlands and Western Isles",
            "Lanarkshire",
            "Lothian",
            "Orkney and Shetland",
            "Renfrewshire",
            "Tayside"
        ],
        "Wales": [
            "Blaenau Gwent",
            "Bridgend",
            "Caerphilly",
            "Cardiff",
            "Carmarthenshire",
            "Ceredigion",
            "Conwy",
            "Denbighshire",
            "Flintshire",
            "Gwynedd",
            " Isle of Anglesey",
            " Merthyr Tydfil",
            "Monmouthshire",
            "Neath Port Talbot",
            "Newport",
            "Pembrokeshire",
            "Powys",
            " Rhondda Cynon Taff",
            " Swansea",
            "Torfaen",
            "Vale of Glamorgan",
            "Wrexham"
        ],
        "Others": []
    }
};

export const COUNTRIES = Object.keys(LOCATION_DATA);
